CREATE TABLE IF NOT EXISTS users (
    userId TEXT PRIMARY KEY,
    username TEXT NOT NULL,
    realName TEXT NOT NULL,
    memory TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS movies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    userId TEXT NOT NULL,
    moovey BOOLEAN NOT NULL
);